version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: service1
    ports:
      - "5000:5000"

  service2:
    build: ./service_2
    container_name: service2
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
